
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_Grub
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.ComboBox CBO_Entry;

		private global::Gtk.Label LIB_Title;

		private global::Gtk.Entry SAI_Title;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView TXT_Options;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button BTN_Apply;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_Grub
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_Grub";
			// Container child frugalmonotools.WID_Grub.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.CBO_Entry = global::Gtk.ComboBox.NewText ();
			this.CBO_Entry.Name = "CBO_Entry";
			this.vbox1.Add (this.CBO_Entry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.CBO_Entry]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.LIB_Title = new global::Gtk.Label ();
			this.LIB_Title.Name = "LIB_Title";
			this.LIB_Title.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
			this.vbox1.Add (this.LIB_Title);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.LIB_Title]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.SAI_Title = new global::Gtk.Entry ();
			this.SAI_Title.CanFocus = true;
			this.SAI_Title.Name = "SAI_Title";
			this.SAI_Title.IsEditable = true;
			this.SAI_Title.InvisibleChar = '•';
			this.vbox1.Add (this.SAI_Title);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.SAI_Title]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TXT_Options = new global::Gtk.TextView ();
			this.TXT_Options.CanFocus = true;
			this.TXT_Options.Name = "TXT_Options";
			this.GtkScrolledWindow.Add (this.TXT_Options);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w5.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BTN_Apply = new global::Gtk.Button ();
			this.BTN_Apply.CanFocus = true;
			this.BTN_Apply.Name = "BTN_Apply";
			this.BTN_Apply.UseUnderline = true;
			// Container child BTN_Apply.Gtk.Container+ContainerChild
			global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w7 = new global::Gtk.HBox ();
			w7.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w7.Add (w8);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w10 = new global::Gtk.Label ();
			w10.LabelProp = global::Mono.Unix.Catalog.GetString ("Apply");
			w10.UseUnderline = true;
			w7.Add (w10);
			w6.Add (w7);
			this.BTN_Apply.Add (w6);
			this.hbox1.Add (this.BTN_Apply);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.BTN_Apply]));
			w14.PackType = ((global::Gtk.PackType)(1));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
