
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_Xorg
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label2;

		private global::Gtk.Entry SAI_Layout;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Label LIB_Lspci;

		private global::Gtk.ComboBoxEntry CBO_GraphicalDevice;

		private global::Gtk.Button BTN_Synaptics;

		private global::Gtk.CheckButton INT_Numlock;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Button BTN_Xorg;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_Xorg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_Xorg";
			// Container child frugalmonotools.WID_Xorg.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Layout");
			this.hbox13.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.SAI_Layout = new global::Gtk.Entry ();
			this.SAI_Layout.CanFocus = true;
			this.SAI_Layout.Name = "SAI_Layout";
			this.SAI_Layout.IsEditable = true;
			this.SAI_Layout.MaxLength = 10;
			this.SAI_Layout.InvisibleChar = '●';
			this.hbox13.Add (this.SAI_Layout);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.SAI_Layout]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			w2.Expand = false;
			this.vbox6.Add (this.hbox13);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox13]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.LIB_Lspci = new global::Gtk.Label ();
			this.LIB_Lspci.Name = "LIB_Lspci";
			this.LIB_Lspci.LabelProp = global::Mono.Unix.Catalog.GetString ("lspci");
			this.hbox16.Add (this.LIB_Lspci);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.LIB_Lspci]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.CBO_GraphicalDevice = global::Gtk.ComboBoxEntry.NewText ();
			this.CBO_GraphicalDevice.Name = "CBO_GraphicalDevice";
			this.hbox16.Add (this.CBO_GraphicalDevice);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.CBO_GraphicalDevice]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox6.Add (this.hbox16);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox16]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.BTN_Synaptics = new global::Gtk.Button ();
			this.BTN_Synaptics.CanFocus = true;
			this.BTN_Synaptics.Name = "BTN_Synaptics";
			this.BTN_Synaptics.UseUnderline = true;
			this.BTN_Synaptics.Label = global::Mono.Unix.Catalog.GetString ("xf86-input-synaptics is not installed. Click here to install it.");
			this.vbox6.Add (this.BTN_Synaptics);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.BTN_Synaptics]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.INT_Numlock = new global::Gtk.CheckButton ();
			this.INT_Numlock.CanFocus = true;
			this.INT_Numlock.Name = "INT_Numlock";
			this.INT_Numlock.Label = global::Mono.Unix.Catalog.GetString ("Enable numlock on startX");
			this.INT_Numlock.DrawIndicator = true;
			this.INT_Numlock.UseUnderline = true;
			this.vbox6.Add (this.INT_Numlock);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.INT_Numlock]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.BTN_Xorg = new global::Gtk.Button ();
			this.BTN_Xorg.CanFocus = true;
			this.BTN_Xorg.Name = "BTN_Xorg";
			this.BTN_Xorg.UseUnderline = true;
			this.BTN_Xorg.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.hbox14.Add (this.BTN_Xorg);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.BTN_Xorg]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox6.Add (this.hbox14);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox14]));
			w10.Position = 6;
			w10.Expand = false;
			w10.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.BTN_Synaptics.Clicked += new global::System.EventHandler (this.OnBTNSynapticsClicked);
			this.BTN_Xorg.Clicked += new global::System.EventHandler (this.OnBTNXorgClicked);
		}
	}
}
