
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_Config
	{
		private global::Gtk.VBox vbox8;

		private global::Gtk.CheckButton INT_CheckStartup;

		private global::Gtk.CheckButton INT_StartWithXSession;

		private global::Gtk.CheckButton INT_ShowNotif;

		private global::Gtk.CheckButton INT_ShowSplash;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Button BTN_SaveConf;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_Config
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_Config";
			// Container child frugalmonotools.WID_Config.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.INT_CheckStartup = new global::Gtk.CheckButton ();
			this.INT_CheckStartup.CanFocus = true;
			this.INT_CheckStartup.Name = "INT_CheckStartup";
			this.INT_CheckStartup.Label = global::Mono.Unix.Catalog.GetString ("Check update on frugal-mono-tools startup");
			this.INT_CheckStartup.DrawIndicator = true;
			this.INT_CheckStartup.UseUnderline = true;
			this.vbox8.Add (this.INT_CheckStartup);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.INT_CheckStartup]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.INT_StartWithXSession = new global::Gtk.CheckButton ();
			this.INT_StartWithXSession.CanFocus = true;
			this.INT_StartWithXSession.Name = "INT_StartWithXSession";
			this.INT_StartWithXSession.Label = global::Mono.Unix.Catalog.GetString ("Start with X session");
			this.INT_StartWithXSession.DrawIndicator = true;
			this.INT_StartWithXSession.UseUnderline = true;
			this.vbox8.Add (this.INT_StartWithXSession);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.INT_StartWithXSession]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.INT_ShowNotif = new global::Gtk.CheckButton ();
			this.INT_ShowNotif.CanFocus = true;
			this.INT_ShowNotif.Name = "INT_ShowNotif";
			this.INT_ShowNotif.Label = global::Mono.Unix.Catalog.GetString ("Show notification");
			this.INT_ShowNotif.Active = true;
			this.INT_ShowNotif.DrawIndicator = true;
			this.INT_ShowNotif.UseUnderline = true;
			this.vbox8.Add (this.INT_ShowNotif);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.INT_ShowNotif]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.INT_ShowSplash = new global::Gtk.CheckButton ();
			this.INT_ShowSplash.CanFocus = true;
			this.INT_ShowSplash.Name = "INT_ShowSplash";
			this.INT_ShowSplash.Label = global::Mono.Unix.Catalog.GetString ("Show splash screen");
			this.INT_ShowSplash.Active = true;
			this.INT_ShowSplash.DrawIndicator = true;
			this.INT_ShowSplash.UseUnderline = true;
			this.vbox8.Add (this.INT_ShowSplash);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.INT_ShowSplash]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.BTN_SaveConf = new global::Gtk.Button ();
			this.BTN_SaveConf.CanFocus = true;
			this.BTN_SaveConf.Name = "BTN_SaveConf";
			this.BTN_SaveConf.UseUnderline = true;
			this.BTN_SaveConf.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.hbox21.Add (this.BTN_SaveConf);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.BTN_SaveConf]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox8.Add (this.hbox21);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox21]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox8);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.BTN_SaveConf.Clicked += new global::System.EventHandler (this.OnBTNSaveConfClicked);
		}
	}
}
