
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class DiagGrub
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Entry SAI_Entry;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView TXT_Options;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button BTN_Cancel;
		private global::Gtk.Button BTN_Add;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.DiagGrub
			this.Name = "frugalmonotools.DiagGrub";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child frugalmonotools.DiagGrub.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.SAI_Entry = new global::Gtk.Entry ();
			this.SAI_Entry.CanFocus = true;
			this.SAI_Entry.Name = "SAI_Entry";
			this.SAI_Entry.IsEditable = true;
			this.SAI_Entry.InvisibleChar = '•';
			this.vbox3.Add (this.SAI_Entry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.SAI_Entry]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TXT_Options = new global::Gtk.TextView ();
			this.TXT_Options.CanFocus = true;
			this.TXT_Options.Name = "TXT_Options";
			this.GtkScrolledWindow.Add (this.TXT_Options);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w4.Position = 1;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox3]));
			w5.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 2;
			// Internal child frugalmonotools.DiagGrub.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "__gtksharp_69_Stetic_TopLevelDialog_ActionArea";
			// Container child __gtksharp_69_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.BTN_Cancel = new global::Gtk.Button ();
			this.BTN_Cancel.CanFocus = true;
			this.BTN_Cancel.Name = "BTN_Cancel";
			this.BTN_Cancel.UseUnderline = true;
			this.BTN_Cancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.AddActionWidget (this.BTN_Cancel, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.BTN_Cancel]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child __gtksharp_69_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.BTN_Add = new global::Gtk.Button ();
			this.BTN_Add.CanFocus = true;
			this.BTN_Add.Name = "BTN_Add";
			this.BTN_Add.UseUnderline = true;
			this.BTN_Add.Label = global::Mono.Unix.Catalog.GetString ("Add");
			this.AddActionWidget (this.BTN_Add, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.BTN_Add]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.BTN_Cancel.Clicked += new global::System.EventHandler (this.OnButton36Clicked);
			this.BTN_Add.Clicked += new global::System.EventHandler (this.OnBTNAddClicked);
		}
	}
}
