
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_Config
	{
		private global::Gtk.VBox vbox8;
		private global::Gtk.CheckButton INT_CheckStartup;
		private global::Gtk.CheckButton INT_StartWithXSession;
		private global::Gtk.CheckButton INT_ShowNotif;
		private global::Gtk.CheckButton INT_ShowSplash;
		private global::Gtk.HBox hbox21;
		private global::Gtk.Button BTN_SaveConf;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_Config
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_Config";
			// Container child frugalmonotools.WID_Config.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.INT_CheckStartup = new global::Gtk.CheckButton ();
			this.INT_CheckStartup.CanFocus = true;
			this.INT_CheckStartup.Name = "INT_CheckStartup";
			this.INT_CheckStartup.Label = global::Mono.Unix.Catalog.GetString ("Check update on frugal-mono-tools startup");
			this.INT_CheckStartup.DrawIndicator = true;
			this.INT_CheckStartup.UseUnderline = true;
			this.vbox8.Add (this.INT_CheckStartup);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.INT_CheckStartup]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.INT_StartWithXSession = new global::Gtk.CheckButton ();
			this.INT_StartWithXSession.CanFocus = true;
			this.INT_StartWithXSession.Name = "INT_StartWithXSession";
			this.INT_StartWithXSession.Label = global::Mono.Unix.Catalog.GetString ("Start with X session");
			this.INT_StartWithXSession.DrawIndicator = true;
			this.INT_StartWithXSession.UseUnderline = true;
			this.vbox8.Add (this.INT_StartWithXSession);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.INT_StartWithXSession]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.INT_ShowNotif = new global::Gtk.CheckButton ();
			this.INT_ShowNotif.CanFocus = true;
			this.INT_ShowNotif.Name = "INT_ShowNotif";
			this.INT_ShowNotif.Label = global::Mono.Unix.Catalog.GetString ("Show notification");
			this.INT_ShowNotif.Active = true;
			this.INT_ShowNotif.DrawIndicator = true;
			this.INT_ShowNotif.UseUnderline = true;
			this.vbox8.Add (this.INT_ShowNotif);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.INT_ShowNotif]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.INT_ShowSplash = new global::Gtk.CheckButton ();
			this.INT_ShowSplash.CanFocus = true;
			this.INT_ShowSplash.Name = "INT_ShowSplash";
			this.INT_ShowSplash.Label = global::Mono.Unix.Catalog.GetString ("Show splash screen");
			this.INT_ShowSplash.Active = true;
			this.INT_ShowSplash.DrawIndicator = true;
			this.INT_ShowSplash.UseUnderline = true;
			this.vbox8.Add (this.INT_ShowSplash);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.INT_ShowSplash]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.BTN_SaveConf = new global::Gtk.Button ();
			this.BTN_SaveConf.CanFocus = true;
			this.BTN_SaveConf.Name = "BTN_SaveConf";
			this.BTN_SaveConf.UseUnderline = true;
			// Container child BTN_SaveConf.Gtk.Container+ContainerChild
			global::Gtk.Alignment w5 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w6 = new global::Gtk.HBox ();
			w6.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w6.Add (w7);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w9 = new global::Gtk.Label ();
			w9.LabelProp = global::Mono.Unix.Catalog.GetString ("Apply");
			w9.UseUnderline = true;
			w6.Add (w9);
			w5.Add (w6);
			this.BTN_SaveConf.Add (w5);
			this.hbox21.Add (this.BTN_SaveConf);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.BTN_SaveConf]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox8.Add (this.hbox21);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox21]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			this.Add (this.vbox8);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.BTN_SaveConf.Clicked += new global::System.EventHandler (this.OnBTNSaveConfClicked);
		}
	}
}
