
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_Pkg
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox11;

		private global::Gtk.ComboBox CBO_Repo;

		private global::Gtk.Entry SAI_pkg;

		private global::Gtk.Button BTN_Search;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeviewpkg;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button BTN_Uninstall;

		private global::Gtk.Button BTN_Install;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_Pkg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_Pkg";
			// Container child frugalmonotools.WID_Pkg.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.CBO_Repo = global::Gtk.ComboBox.NewText ();
			this.CBO_Repo.Name = "CBO_Repo";
			this.hbox11.Add (this.CBO_Repo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.CBO_Repo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.SAI_pkg = new global::Gtk.Entry ();
			this.SAI_pkg.TooltipMarkup = "Package search";
			this.SAI_pkg.CanFocus = true;
			this.SAI_pkg.Name = "SAI_pkg";
			this.SAI_pkg.IsEditable = true;
			this.SAI_pkg.InvisibleChar = '●';
			this.hbox11.Add (this.SAI_pkg);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.SAI_pkg]));
			w2.Position = 1;
			// Container child hbox11.Gtk.Box+BoxChild
			this.BTN_Search = new global::Gtk.Button ();
			this.BTN_Search.CanFocus = true;
			this.BTN_Search.Name = "BTN_Search";
			this.BTN_Search.UseUnderline = true;
			// Container child BTN_Search.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("_Search");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.BTN_Search.Add (w3);
			this.hbox11.Add (this.BTN_Search);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.BTN_Search]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox4.Add (this.hbox11);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox11]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewpkg = new global::Gtk.TreeView ();
			this.treeviewpkg.CanFocus = true;
			this.treeviewpkg.Name = "treeviewpkg";
			this.GtkScrolledWindow.Add (this.treeviewpkg);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w14.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.BTN_Uninstall = new global::Gtk.Button ();
			this.BTN_Uninstall.CanFocus = true;
			this.BTN_Uninstall.Name = "BTN_Uninstall";
			this.BTN_Uninstall.UseUnderline = true;
			// Container child BTN_Uninstall.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w19.LabelProp = global::Mono.Unix.Catalog.GetString ("Uninstall");
			w19.UseUnderline = true;
			w16.Add (w19);
			w15.Add (w16);
			this.BTN_Uninstall.Add (w15);
			this.hbox12.Add (this.BTN_Uninstall);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.BTN_Uninstall]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.BTN_Install = new global::Gtk.Button ();
			this.BTN_Install.CanFocus = true;
			this.BTN_Install.Name = "BTN_Install";
			this.BTN_Install.UseUnderline = true;
			// Container child BTN_Install.Gtk.Container+ContainerChild
			global::Gtk.Alignment w24 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w25 = new global::Gtk.HBox ();
			w25.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("frugalmonotools.Pictures.icons.update.png");
			w25.Add (w26);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.LabelProp = global::Mono.Unix.Catalog.GetString ("_Install");
			w28.UseUnderline = true;
			w25.Add (w28);
			w24.Add (w25);
			this.BTN_Install.Add (w24);
			this.hbox12.Add (this.BTN_Install);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.BTN_Install]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox4.Add (this.hbox12);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox12]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.CBO_Repo.Changed += new global::System.EventHandler (this.OnCBORepoChanged);
			this.BTN_Search.Clicked += new global::System.EventHandler (this.OnBTNSearchClicked);
			this.BTN_Uninstall.Clicked += new global::System.EventHandler (this.OnBTNUninstallClicked);
			this.BTN_Install.Clicked += new global::System.EventHandler (this.OnBTNInstallClicked);
		}
	}
}
