
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_News
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.ComboBox CBO_TitleNews;

		private global::Gtk.Label LIB_Titre;

		private global::Gtk.Button BTN_Link;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_News
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_News";
			// Container child frugalmonotools.WID_News.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.CBO_TitleNews = global::Gtk.ComboBox.NewText ();
			this.CBO_TitleNews.Name = "CBO_TitleNews";
			this.vbox5.Add (this.CBO_TitleNews);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.CBO_TitleNews]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.LIB_Titre = new global::Gtk.Label ();
			this.LIB_Titre.Name = "LIB_Titre";
			this.vbox5.Add (this.LIB_Titre);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.LIB_Titre]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.BTN_Link = new global::Gtk.Button ();
			this.BTN_Link.CanFocus = true;
			this.BTN_Link.Name = "BTN_Link";
			this.BTN_Link.UseUnderline = true;
			this.BTN_Link.Label = global::Mono.Unix.Catalog.GetString ("http://www.frugalware.org");
			this.vbox5.Add (this.BTN_Link);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.BTN_Link]));
			w3.Position = 3;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.CBO_TitleNews.Changed += new global::System.EventHandler (this.OnCBOTitleNewsChanged);
		}
	}
}
