
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_Services
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView TREE_Services;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Button BTN_ServiceStart;

		private global::Gtk.Button BTN_ServiceStop;

		private global::Gtk.Button BTN_ServiceDelBoot;

		private global::Gtk.Button BTN_ServiceAddBoot;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_Services
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_Services";
			// Container child frugalmonotools.WID_Services.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.TREE_Services = new global::Gtk.TreeView ();
			this.TREE_Services.CanFocus = true;
			this.TREE_Services.Name = "TREE_Services";
			this.GtkScrolledWindow1.Add (this.TREE_Services);
			this.vbox7.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.GtkScrolledWindow1]));
			w2.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.BTN_ServiceStart = new global::Gtk.Button ();
			this.BTN_ServiceStart.CanFocus = true;
			this.BTN_ServiceStart.Name = "BTN_ServiceStart";
			this.BTN_ServiceStart.UseUnderline = true;
			this.BTN_ServiceStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.hbox20.Add (this.BTN_ServiceStart);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.BTN_ServiceStart]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.BTN_ServiceStop = new global::Gtk.Button ();
			this.BTN_ServiceStop.CanFocus = true;
			this.BTN_ServiceStop.Name = "BTN_ServiceStop";
			this.BTN_ServiceStop.UseUnderline = true;
			this.BTN_ServiceStop.Label = global::Mono.Unix.Catalog.GetString ("Stop");
			this.hbox20.Add (this.BTN_ServiceStop);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.BTN_ServiceStop]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.BTN_ServiceDelBoot = new global::Gtk.Button ();
			this.BTN_ServiceDelBoot.CanFocus = true;
			this.BTN_ServiceDelBoot.Name = "BTN_ServiceDelBoot";
			this.BTN_ServiceDelBoot.UseUnderline = true;
			this.BTN_ServiceDelBoot.Label = global::Mono.Unix.Catalog.GetString ("Don't start it on boot");
			this.hbox20.Add (this.BTN_ServiceDelBoot);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.BTN_ServiceDelBoot]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.BTN_ServiceAddBoot = new global::Gtk.Button ();
			this.BTN_ServiceAddBoot.CanFocus = true;
			this.BTN_ServiceAddBoot.Name = "BTN_ServiceAddBoot";
			this.BTN_ServiceAddBoot.UseUnderline = true;
			this.BTN_ServiceAddBoot.Label = global::Mono.Unix.Catalog.GetString ("Start it on boot");
			this.hbox20.Add (this.BTN_ServiceAddBoot);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.BTN_ServiceAddBoot]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox7.Add (this.hbox20);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox20]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.BTN_ServiceStart.Hide ();
			this.BTN_ServiceStop.Hide ();
			this.BTN_ServiceDelBoot.Hide ();
			this.BTN_ServiceAddBoot.Hide ();
			this.Hide ();
			this.BTN_ServiceStart.Clicked += new global::System.EventHandler (this.OnBTNServiceStartClicked);
			this.BTN_ServiceStop.Clicked += new global::System.EventHandler (this.OnBTNServiceStopClicked);
			this.BTN_ServiceDelBoot.Clicked += new global::System.EventHandler (this.OnBTNServiceDelBootClicked);
			this.BTN_ServiceAddBoot.Clicked += new global::System.EventHandler (this.OnBTNServiceAddBootClicked);
		}
	}
}
