
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class Fen_Menu
	{
		private global::Gtk.HBox HBOX_Menu;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView TREE_Menu;

		private global::Gtk.HBox HBOX_Details;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.Fen_Menu
			this.Name = "frugalmonotools.Fen_Menu";
			this.Title = global::Mono.Unix.Catalog.GetString ("Frugalware tweak !");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("frugalmonotools.Pictures.fw.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child frugalmonotools.Fen_Menu.Gtk.Container+ContainerChild
			this.HBOX_Menu = new global::Gtk.HBox ();
			this.HBOX_Menu.Name = "HBOX_Menu";
			this.HBOX_Menu.Spacing = 6;
			// Container child HBOX_Menu.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TREE_Menu = new global::Gtk.TreeView ();
			this.TREE_Menu.WidthRequest = 50;
			this.TREE_Menu.HeightRequest = 50;
			this.TREE_Menu.CanFocus = true;
			this.TREE_Menu.Name = "TREE_Menu";
			this.GtkScrolledWindow.Add (this.TREE_Menu);
			this.HBOX_Menu.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.HBOX_Menu[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child HBOX_Menu.Gtk.Box+BoxChild
			this.HBOX_Details = new global::Gtk.HBox ();
			this.HBOX_Details.Name = "HBOX_Details";
			this.HBOX_Details.Spacing = 6;
			this.HBOX_Menu.Add (this.HBOX_Details);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.HBOX_Menu[this.HBOX_Details]));
			w3.Position = 1;
			this.Add (this.HBOX_Menu);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 892;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
