
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_Logs
	{
		private global::Gtk.Notebook notebook1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView TXT_Dmesg;
		private global::Gtk.Label label1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView TXT_Xorg;
		private global::Gtk.Label label2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TextView TXT_pacmang2;
		private global::Gtk.Label label3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView TXT_XsessionErrors;
		private global::Gtk.Label label4;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_Logs
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_Logs";
			// Container child frugalmonotools.WID_Logs.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TXT_Dmesg = new global::Gtk.TextView ();
			this.TXT_Dmesg.CanFocus = true;
			this.TXT_Dmesg.Name = "TXT_Dmesg";
			this.GtkScrolledWindow.Add (this.TXT_Dmesg);
			this.notebook1.Add (this.GtkScrolledWindow);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("dmesg");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.TXT_Xorg = new global::Gtk.TextView ();
			this.TXT_Xorg.CanFocus = true;
			this.TXT_Xorg.Name = "TXT_Xorg";
			this.GtkScrolledWindow1.Add (this.TXT_Xorg);
			this.notebook1.Add (this.GtkScrolledWindow1);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow1]));
			w4.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("xorg");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow1, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.TXT_pacmang2 = new global::Gtk.TextView ();
			this.TXT_pacmang2.CanFocus = true;
			this.TXT_pacmang2.Name = "TXT_pacmang2";
			this.GtkScrolledWindow3.Add (this.TXT_pacmang2);
			this.notebook1.Add (this.GtkScrolledWindow3);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow3]));
			w6.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("pacman-g2");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow3, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.TXT_XsessionErrors = new global::Gtk.TextView ();
			this.TXT_XsessionErrors.CanFocus = true;
			this.TXT_XsessionErrors.Name = "TXT_XsessionErrors";
			this.GtkScrolledWindow2.Add (this.TXT_XsessionErrors);
			this.notebook1.Add (this.GtkScrolledWindow2);
			global::Gtk.Notebook.NotebookChild w8 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow2]));
			w8.Position = 3;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("xsession-errors");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow2, this.label4);
			this.label4.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
