
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_Pkg
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox11;

		private global::Gtk.ComboBox CBO_Repo;

		private global::Gtk.Entry SAI_pkg;

		private global::Gtk.Button BTN_Search;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeviewpkg;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button BTN_Uninstall;

		private global::Gtk.Button BTN_Install;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_Pkg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_Pkg";
			// Container child frugalmonotools.WID_Pkg.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.CBO_Repo = global::Gtk.ComboBox.NewText ();
			this.CBO_Repo.Name = "CBO_Repo";
			this.hbox11.Add (this.CBO_Repo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.CBO_Repo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.SAI_pkg = new global::Gtk.Entry ();
			this.SAI_pkg.TooltipMarkup = "Package search";
			this.SAI_pkg.CanFocus = true;
			this.SAI_pkg.Name = "SAI_pkg";
			this.SAI_pkg.IsEditable = true;
			this.SAI_pkg.InvisibleChar = '●';
			this.hbox11.Add (this.SAI_pkg);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.SAI_pkg]));
			w2.Position = 1;
			// Container child hbox11.Gtk.Box+BoxChild
			this.BTN_Search = new global::Gtk.Button ();
			this.BTN_Search.CanFocus = true;
			this.BTN_Search.Name = "BTN_Search";
			this.BTN_Search.UseUnderline = true;
			this.BTN_Search.Label = global::Mono.Unix.Catalog.GetString ("Search");
			this.hbox11.Add (this.BTN_Search);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.BTN_Search]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox4.Add (this.hbox11);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox11]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewpkg = new global::Gtk.TreeView ();
			this.treeviewpkg.CanFocus = true;
			this.treeviewpkg.Name = "treeviewpkg";
			this.GtkScrolledWindow.Add (this.treeviewpkg);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w6.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.BTN_Uninstall = new global::Gtk.Button ();
			this.BTN_Uninstall.CanFocus = true;
			this.BTN_Uninstall.Name = "BTN_Uninstall";
			this.BTN_Uninstall.UseUnderline = true;
			this.BTN_Uninstall.Label = global::Mono.Unix.Catalog.GetString ("Uninstall");
			this.hbox12.Add (this.BTN_Uninstall);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.BTN_Uninstall]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.BTN_Install = new global::Gtk.Button ();
			this.BTN_Install.CanFocus = true;
			this.BTN_Install.Name = "BTN_Install";
			this.BTN_Install.UseUnderline = true;
			this.BTN_Install.Label = global::Mono.Unix.Catalog.GetString ("Install");
			this.hbox12.Add (this.BTN_Install);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.BTN_Install]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox4.Add (this.hbox12);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox12]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.CBO_Repo.Changed += new global::System.EventHandler (this.OnCBORepoChanged);
			this.BTN_Search.Clicked += new global::System.EventHandler (this.OnBTNSearchClicked);
			this.BTN_Uninstall.Clicked += new global::System.EventHandler (this.OnBTNUninstallClicked);
			this.BTN_Install.Clicked += new global::System.EventHandler (this.OnBTNInstallClicked);
		}
	}
}
