using System;
using System.Runtime.InteropServices;
using System.Collections.Generic;
 
namespace frugalmonotools
{
	
	
	public class PacmanG2
	{
		//don't use c# binding generated by swig
		[DllImport("libpacman.so")]
		private static extern int pacman_initialize(string root);
		[DllImport("libpacman.so")]
		private static extern int pacman_parse_config(string file, EnumRepoProcDelegate callback,string this_section);
		private delegate void EnumRepoProcDelegate(string section, string lParam);
		
		//const
		private const int pm_errno = -1;
		private const string cch_pacmanconf ="/etc/pacman-g2.conf";
		
		//public
		public List<string> fwRepo = new List<string>(); 
		
		private void EnumRepoProc(string section, string lParam)
		{
			fwRepo.Add(section);
		}
		public PacmanG2 ()
		{
			try{
				EnumRepoProcDelegate _cd_db = new EnumRepoProcDelegate(EnumRepoProc);
				if (pacman_initialize("/")!=pm_errno)
				{
					pacman_parse_config(cch_pacmanconf,_cd_db,"");
				}
				
			}
			catch{}
		}

	}
}

