
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_LoginManager
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Image image1;
		private global::Gtk.CheckButton INT_XDM;
		private global::Gtk.Label LIB_XDM;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Image image2;
		private global::Gtk.CheckButton INT_LXDM;
		private global::Gtk.Label LIB_LXDM;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Image image3;
		private global::Gtk.CheckButton INT_Slim;
		private global::Gtk.Label LIB_SLIM;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Image image4;
		private global::Gtk.CheckButton INT_GDM;
		private global::Gtk.Label LIB_GDM;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Image image5;
		private global::Gtk.CheckButton INT_KDM;
		private global::Gtk.Label LIB_KDM;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label LIB_Root;
		private global::Gtk.Button BTN_LoginManager;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_LoginManager
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_LoginManager";
			// Container child frugalmonotools.WID_LoginManager.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("frugalmonotools.Pictures.xorglogo.png");
			this.hbox5.Add (this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.INT_XDM = new global::Gtk.CheckButton ();
			this.INT_XDM.CanFocus = true;
			this.INT_XDM.Name = "INT_XDM";
			this.INT_XDM.Label = global::Mono.Unix.Catalog.GetString ("Use XDM");
			this.INT_XDM.DrawIndicator = true;
			this.INT_XDM.UseUnderline = true;
			this.hbox5.Add (this.INT_XDM);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.INT_XDM]));
			w2.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.LIB_XDM = new global::Gtk.Label ();
			this.LIB_XDM.Name = "LIB_XDM";
			this.LIB_XDM.LabelProp = global::Mono.Unix.Catalog.GetString ("Not installed");
			this.hbox5.Add (this.LIB_XDM);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.LIB_XDM]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("frugalmonotools.Pictures.lxdelogo.png");
			this.hbox6.Add (this.image2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.image2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.INT_LXDM = new global::Gtk.CheckButton ();
			this.INT_LXDM.CanFocus = true;
			this.INT_LXDM.Name = "INT_LXDM";
			this.INT_LXDM.Label = global::Mono.Unix.Catalog.GetString ("Use LXDM");
			this.INT_LXDM.DrawIndicator = true;
			this.INT_LXDM.UseUnderline = true;
			this.hbox6.Add (this.INT_LXDM);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.INT_LXDM]));
			w6.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.LIB_LXDM = new global::Gtk.Label ();
			this.LIB_LXDM.Name = "LIB_LXDM";
			this.LIB_LXDM.LabelProp = global::Mono.Unix.Catalog.GetString ("Not installed");
			this.hbox6.Add (this.LIB_LXDM);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.LIB_LXDM]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("frugalmonotools.Pictures.xfcelogo.png");
			this.hbox7.Add (this.image3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.image3]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.INT_Slim = new global::Gtk.CheckButton ();
			this.INT_Slim.CanFocus = true;
			this.INT_Slim.Name = "INT_Slim";
			this.INT_Slim.Label = global::Mono.Unix.Catalog.GetString ("Use Slim");
			this.INT_Slim.DrawIndicator = true;
			this.INT_Slim.UseUnderline = true;
			this.hbox7.Add (this.INT_Slim);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.INT_Slim]));
			w10.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.LIB_SLIM = new global::Gtk.Label ();
			this.LIB_SLIM.Name = "LIB_SLIM";
			this.LIB_SLIM.LabelProp = global::Mono.Unix.Catalog.GetString ("Not installed");
			this.hbox7.Add (this.LIB_SLIM);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.LIB_SLIM]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox3.Add (this.hbox7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("frugalmonotools.Pictures.gnomelogo.png");
			this.hbox9.Add (this.image4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.image4]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.INT_GDM = new global::Gtk.CheckButton ();
			this.INT_GDM.CanFocus = true;
			this.INT_GDM.Name = "INT_GDM";
			this.INT_GDM.Label = global::Mono.Unix.Catalog.GetString ("Use GDM");
			this.INT_GDM.DrawIndicator = true;
			this.INT_GDM.UseUnderline = true;
			this.hbox9.Add (this.INT_GDM);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.INT_GDM]));
			w14.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.LIB_GDM = new global::Gtk.Label ();
			this.LIB_GDM.Name = "LIB_GDM";
			this.LIB_GDM.LabelProp = global::Mono.Unix.Catalog.GetString ("Not installed");
			this.hbox9.Add (this.LIB_GDM);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.LIB_GDM]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox3.Add (this.hbox9);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox9]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("frugalmonotools.Pictures.kdelogo.png");
			this.hbox10.Add (this.image5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.image5]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.INT_KDM = new global::Gtk.CheckButton ();
			this.INT_KDM.CanFocus = true;
			this.INT_KDM.Name = "INT_KDM";
			this.INT_KDM.Label = global::Mono.Unix.Catalog.GetString ("Use KDM");
			this.INT_KDM.DrawIndicator = true;
			this.INT_KDM.UseUnderline = true;
			this.hbox10.Add (this.INT_KDM);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.INT_KDM]));
			w18.Position = 1;
			// Container child hbox10.Gtk.Box+BoxChild
			this.LIB_KDM = new global::Gtk.Label ();
			this.LIB_KDM.Name = "LIB_KDM";
			this.LIB_KDM.LabelProp = global::Mono.Unix.Catalog.GetString ("Not installed");
			this.hbox10.Add (this.LIB_KDM);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.LIB_KDM]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox3.Add (this.hbox10);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox10]));
			w20.Position = 4;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.LIB_Root = new global::Gtk.Label ();
			this.LIB_Root.Name = "LIB_Root";
			this.LIB_Root.LabelProp = global::Mono.Unix.Catalog.GetString ("Can't save, should be started as root");
			this.hbox8.Add (this.LIB_Root);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.LIB_Root]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.BTN_LoginManager = new global::Gtk.Button ();
			this.BTN_LoginManager.CanFocus = true;
			this.BTN_LoginManager.Name = "BTN_LoginManager";
			this.BTN_LoginManager.UseUnderline = true;
			// Container child BTN_LoginManager.Gtk.Container+ContainerChild
			global::Gtk.Alignment w22 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w23 = new global::Gtk.HBox ();
			w23.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w24 = new global::Gtk.Image ();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w23.Add (w24);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w26 = new global::Gtk.Label ();
			w26.LabelProp = global::Mono.Unix.Catalog.GetString ("Apply");
			w26.UseUnderline = true;
			w23.Add (w26);
			w22.Add (w23);
			this.BTN_LoginManager.Add (w22);
			this.hbox8.Add (this.BTN_LoginManager);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.BTN_LoginManager]));
			w30.PackType = ((global::Gtk.PackType)(1));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox3.Add (this.hbox8);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
			w31.PackType = ((global::Gtk.PackType)(1));
			w31.Position = 5;
			w31.Expand = false;
			w31.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.INT_XDM.Clicked += new global::System.EventHandler (this.OnINTXDMClicked);
			this.INT_LXDM.Clicked += new global::System.EventHandler (this.OnINTLXDMClicked);
			this.INT_Slim.Clicked += new global::System.EventHandler (this.OnINTSlimClicked);
			this.INT_GDM.Clicked += new global::System.EventHandler (this.OnINTGDMClicked);
			this.INT_KDM.Clicked += new global::System.EventHandler (this.OnINTKDMClicked);
			this.BTN_LoginManager.Clicked += new global::System.EventHandler (this.OnBTNLoginManagerClicked);
		}
	}
}
