
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class FEN_Debug
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView SortieAPPLI;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.FEN_Debug
			this.Name = "frugalmonotools.FEN_Debug";
			this.Title = global::Mono.Unix.Catalog.GetString ("DEBUG");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child frugalmonotools.FEN_Debug.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.SortieAPPLI = new global::Gtk.TextView ();
			this.SortieAPPLI.Buffer.Text = "DEBUG:\n";
			this.SortieAPPLI.CanFocus = true;
			this.SortieAPPLI.Name = "SortieAPPLI";
			this.GtkScrolledWindow.Add (this.SortieAPPLI);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
