
// This file has been generated by the GUI designer. Do not modify.
namespace frugalmonotools
{
	public partial class WID_UpdateConf
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView TREE_UpdateConf;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button BTN_SeeDiff;
		private global::Gtk.Button BTN_Replace;
		private global::Gtk.Button BTN_Delete;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget frugalmonotools.WID_UpdateConf
			global::Stetic.BinContainer.Attach (this);
			this.Name = "frugalmonotools.WID_UpdateConf";
			// Container child frugalmonotools.WID_UpdateConf.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TREE_UpdateConf = new global::Gtk.TreeView ();
			this.TREE_UpdateConf.CanFocus = true;
			this.TREE_UpdateConf.Name = "TREE_UpdateConf";
			this.GtkScrolledWindow.Add (this.TREE_UpdateConf);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BTN_SeeDiff = new global::Gtk.Button ();
			this.BTN_SeeDiff.CanFocus = true;
			this.BTN_SeeDiff.Name = "BTN_SeeDiff";
			this.BTN_SeeDiff.UseUnderline = true;
			this.BTN_SeeDiff.Label = global::Mono.Unix.Catalog.GetString ("See diff");
			this.hbox1.Add (this.BTN_SeeDiff);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BTN_SeeDiff]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BTN_Replace = new global::Gtk.Button ();
			this.BTN_Replace.CanFocus = true;
			this.BTN_Replace.Name = "BTN_Replace";
			this.BTN_Replace.UseUnderline = true;
			this.BTN_Replace.Label = global::Mono.Unix.Catalog.GetString ("Replace");
			this.hbox1.Add (this.BTN_Replace);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BTN_Replace]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.BTN_Delete = new global::Gtk.Button ();
			this.BTN_Delete.CanFocus = true;
			this.BTN_Delete.Name = "BTN_Delete";
			this.BTN_Delete.UseUnderline = true;
			this.BTN_Delete.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			this.hbox1.Add (this.BTN_Delete);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.BTN_Delete]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.BTN_SeeDiff.Clicked += new global::System.EventHandler (this.OnBTNSeeDiffClicked);
			this.BTN_Replace.Clicked += new global::System.EventHandler (this.OnBTNReplaceClicked);
			this.BTN_Delete.Clicked += new global::System.EventHandler (this.OnBTNDeleteClicked);
		}
	}
}
